# Generated by Django 5.2.3 on 2025-06-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_rename_collection_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateogry',
            new_name='Category',
        ),
    ]
