# Generated by Django 5.2.3 on 2025-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
